namespace: dynamixel_manager
serial_ports:
  dynamixel_port:
     #port_name: "/dev/serial/by-id/usb-FTDI_FT232R_USB_UART_AD01UYX2-if00-port0"
     port_name: "/dev/ttyACM0"
     baud_rate: 1000000
     min_motor_id: 1
     max_motor_id: 21
     update_rate: 100
